export const CATALOGO_PREV: any = {
    "eSocial — Escrituração Digital": [
        { id: "eSocial-S1000", sigla: "S-1000", nome: "Informações do Empregador/Contribuinte", prazo: "Eventual", desc: "Cadastro inicial ou alteração dos dados do empregador." },
        { id: "eSocial-S1200", sigla: "S-1200", nome: "Remuneração de Trabalhador vinculado ao RGPS", prazo: "Mensal", desc: "Competência até dia 7 do mês seguinte." },
        { id: "eSocial-S1202", sigla: "S-1202", nome: "Remuneração de Servidor vinculado ao RPPS", prazo: "Mensal", desc: "Órgãos públicos com regime próprio." },
        { id: "eSocial-S1207", sigla: "S-1207", nome: "Benefícios Previdenciários — INSS/RPPS", prazo: "Mensal", desc: "Compensação previdenciária." },
        { id: "eSocial-S2200", sigla: "S-2200", nome: "Cadastramento Inicial de Vínculo / Admissão", prazo: "Eventual", desc: "Até 1 dia antes do início da atividade." },
        { id: "eSocial-S2205", sigla: "S-2205", nome: "Alteração de Dados Cadastrais do Trabalhador", prazo: "Eventual", desc: "Prazo: 15 dias após a ocorrência." },
        { id: "eSocial-S2206", sigla: "S-2206", nome: "Alteração de Contrato de Trabalho", prazo: "Eventual", desc: "Prazo: até o dia 7 do mês seguinte." },
        { id: "eSocial-S2210", sigla: "S-2210", nome: "Comunicação de Acidente de Trabalho (CAT)", prazo: "Eventual", desc: "Até 1 dia útil após o acidente." },
        { id: "eSocial-S2230", sigla: "S-2230", nome: "Afastamento Temporário", prazo: "Eventual", desc: "INSS, licença, falta justificada." },
        { id: "eSocial-S2299", sigla: "S-2299", nome: "Desligamento / Rescisão Contratual", prazo: "Eventual", desc: "Até 10 dias corridos após o desligamento." },
        { id: "eSocial-S2300", sigla: "S-2300", nome: "Trabalhador Sem Vínculo — TSVE Início", prazo: "Eventual", desc: "Autônomos, diretores, estagiários." },
        { id: "eSocial-S2399", sigla: "S-2399", nome: "Trabalhador Sem Vínculo — TSVE Término", prazo: "Eventual", desc: "Encerramento de serviço prestado." },
        { id: "eSocial-S2400", sigla: "S-2400", nome: "Cadastro de Benefício Previdenciário", prazo: "Eventual", desc: "Para empregadores com RPPS." },
        { id: "eSocial-S2500", sigla: "S-2500", nome: "Processo Trabalhista", prazo: "Eventual", desc: "Decisões judiciais trabalhistas." },
        { id: "eSocial-S2501", sigla: "S-2501", nome: "Informações de Contribuições — Processo Trabalhista", prazo: "Eventual", desc: "Após decisão judicial." },
        { id: "eSocial-S3000", sigla: "S-3000", nome: "Exclusão de Eventos", prazo: "Eventual", desc: "Cancelamento de evento enviado com erro." },
    ],
    "DCTFWeb — Declaração de Débitos": [
        { id: "DCTFWeb-Mensal", sigla: "DCTFWeb", nome: "DCTFWeb Mensal — Contribuições Previdenciárias", prazo: "Mensal", desc: "Gerada automaticamente a partir do eSocial. Vence dia 15 do mês seguinte." },
        { id: "DCTFWeb-13o", sigla: "DCTFWeb 13°", nome: "DCTFWeb 13° Salário", prazo: "Anual", desc: "Competência dezembro, vence em 20/12." },
        { id: "DCTFWeb-Ferias", sigla: "DCTFWeb Férias", nome: "DCTFWeb Folha de Férias", prazo: "Eventual", desc: "Quando há férias no período." },
    ],
    "FGTS — Fundo de Garantia": [
        { id: "FGTS-Mensal", sigla: "FGTS", nome: "FGTS Mensal — Guia de Recolhimento", prazo: "Mensal", desc: "Vence dia 7 do mês seguinte. 8% sobre remuneração bruta." },
        { id: "FGTS-Rescisao", sigla: "FGTS Res.", nome: "FGTS Rescisório (Multa 40%)", prazo: "Eventual", desc: "Deve ser recolhido até 10 dias após demissão sem justa causa." },
        { id: "FGTS-GRRF", sigla: "GRRF", nome: "GRRF — Guia para Rescisão do Contrato", prazo: "Eventual", desc: "Rescisões, aposentadoria e outras hipóteses de saque." },
        { id: "FGTS-SEFIP", sigla: "SEFIP/GFIP", nome: "SEFIP/GFIP — Casos Residuais", prazo: "Mensal", desc: "Ainda exigido em situações não migradas ao eSocial." },
    ],
    "Folha de Pagamento e Obrigações Acessórias": [
        { id: "FP-Folha", sigla: "Folha", nome: "Folha de Pagamento Mensal", prazo: "Mensal", desc: "Elaboração e arquivo até o 5° dia útil do mês seguinte." },
        { id: "FP-HOLERITE", sigla: "Holerite", nome: "Contracheque / Holerite", prazo: "Mensal", desc: "Entrega ao funcionário até o dia do pagamento." },
        { id: "FP-RAIS", sigla: "RAIS", nome: "RAIS — Relação Anual de Informações Sociais", prazo: "Anual", desc: "Entrega até março do ano seguinte. Portaria MTE." },
        { id: "FP-CAGED", sigla: "CAGED", nome: "CAGED — Cadastro Geral de Empregados e Desempregados", prazo: "Mensal", desc: "Substituído pelo eSocial para empresas obrigadas. Prazo: dia 7." },
        { id: "FP-DIRF-Prev", sigla: "DIRF", nome: "DIRF — Declaração de IR Retido na Fonte (Prev.)", prazo: "Anual", desc: "Fevereiro do ano seguinte. Rendimentos e retenções." },
        { id: "FP-PPP", sigla: "PPP", nome: "PPP — Perfil Profissiográfico Previdenciário", prazo: "Eventual", desc: "Obrigatório na demissão de trabalhador exposto a agentes nocivos." },
        { id: "FP-LTCAT", sigla: "LTCAT", nome: "LTCAT — Laudo Técnico das Condições Ambientais", prazo: "Eventual", desc: "Obrigatório para empresas com exposição a agentes nocivos." },
        { id: "FP-PCMSOe", sigla: "PCMSO", nome: "PCMSO — Programa de Controle Médico de Saúde Ocupacional", prazo: "Anual", desc: "Obrigatório para toda empresa com empregados CLT." },
        { id: "FP-PPRA", sigla: "PPRA/PGR", nome: "PPRA/PGR — Programa de Gerenciamento de Riscos", prazo: "Anual", desc: "Substituído pelo PGR (NR-1). Revisão anual obrigatória." },
    ],
    "Previdência Social — INSS": [
        { id: "INSS-GPS", sigla: "GPS", nome: "GPS — Guia da Previdência Social", prazo: "Mensal", desc: "Vence dia 20 do mês seguinte. Contribuições sobre folha." },
        { id: "INSS-COMP", sigla: "Comp.Prev.", nome: "Compensação Previdenciária (COMPREV)", prazo: "Eventual", desc: "Compensação de benefícios pagos pelo empregador." },
        { id: "INSS-EFD-Reinf", sigla: "EFD-Reinf", nome: "EFD-Reinf — Retenções sobre Serviços", prazo: "Mensal", desc: "Retenção de 11% sobre serviços com cessão de mão de obra." },
    ],
};
